/* ============================================================================
   Kibookal — Corner Tag  (stamps STYLE · LAYOUT in a page corner)
   Every image generated by the studio gets a small, crisp corner badge with its
   active style id and layout id (e.g. "KBS042 · C016"). Composited onto the image
   via canvas AFTER generation, so the text is always correct (never model-garbled).
   Hooked once inside generateImage. Falls back to the un-stamped image on any error
   (e.g. if a provider's CDN blocks cross-origin canvas export).
   Set opts.noCornerTag = true on a call to skip it (e.g. internal/derived renders).
   ========================================================================== */
(function () {
  'use strict';
  const CORNER = 'br';            // 'tl' | 'tr' | 'bl' | 'br'  (default bottom-right)

  function loadImg(url) {
    return new Promise((res, rej) => {
      const i = new Image();
      i.crossOrigin = 'anonymous'; // needed so the canvas isn't tainted → toDataURL works
      i.onload = () => res(i);
      i.onerror = rej;
      i.src = url;
    });
  }
  function pickStyle(prompt, opts) {
    if (opts && opts.styleId) return opts.styleId;
    try { if (window.kbsGetActiveStyleId) { const s = kbsGetActiveStyleId(); if (s) return s; } } catch (e) {}
    const m = String(prompt || '').match(/KBS\d{3}/);
    return m ? m[0] : '';
  }
  function pickLayout(prompt, opts) {
    if (opts && opts.layoutId) return opts.layoutId;
    try { if (window.kbsGetActiveLayout) { const l = kbsGetActiveLayout(); if (l && l.layout_id) return l.layout_id; } } catch (e) {}
    const m = String(prompt || '').match(/\b[CM]\d{3}\b/);   // C016 (comic) or M017 (magazine)
    return m ? m[0] : '';
  }
  function roundRect(ctx, x, y, w, h, r) {
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.arcTo(x + w, y, x + w, y + h, r);
    ctx.arcTo(x + w, y + h, x, y + h, r);
    ctx.arcTo(x, y + h, x, y, r);
    ctx.arcTo(x, y, x + w, y, r);
    ctx.closePath();
  }

  async function stamp(url, prompt, opts) {
    try {
      if (!url || typeof url !== 'string') return url;
      if (opts && opts.noCornerTag) return url;
      const style = pickStyle(prompt, opts);
      const layout = pickLayout(prompt, opts);
      const tag = [style, layout].filter(Boolean).join(' · ');
      if (!tag) return url;

      const img = await loadImg(url);
      const w = img.naturalWidth || img.width, h = img.naturalHeight || img.height;
      if (!w || !h) return url;
      const c = document.createElement('canvas');
      c.width = w; c.height = h;
      const ctx = c.getContext('2d');
      ctx.drawImage(img, 0, 0, w, h);

      const fs = Math.max(12, Math.round(w * 0.020));
      ctx.font = '600 ' + fs + 'px "JetBrains Mono", ui-monospace, "Courier New", monospace';
      const padX = Math.round(fs * 0.7), padY = Math.round(fs * 0.45), m = Math.round(w * 0.018);
      const tw = ctx.measureText(tag).width;
      const bw = Math.round(tw + padX * 2), bh = fs + padY * 2;
      let x, y;
      if (CORNER === 'br') { x = w - m - bw; y = h - m - bh; }
      else if (CORNER === 'bl') { x = m; y = h - m - bh; }
      else if (CORNER === 'tr') { x = w - m - bw; y = m; }
      else { x = m; y = m; }
      const r = Math.round(bh * 0.28);

      ctx.fillStyle = 'rgba(20,16,12,0.60)';
      roundRect(ctx, x, y, bw, bh, r); ctx.fill();
      ctx.strokeStyle = 'rgba(255,255,255,0.20)';
      ctx.lineWidth = Math.max(1, Math.round(fs * 0.06));
      roundRect(ctx, x, y, bw, bh, r); ctx.stroke();
      ctx.fillStyle = 'rgba(255,244,224,0.96)';
      ctx.textBaseline = 'middle'; ctx.textAlign = 'left';
      ctx.fillText(tag, x + padX, y + bh / 2 + 1);

      return c.toDataURL('image/jpeg', 0.92);
    } catch (e) {
      console.warn('[corner-tag] skipped (kept original):', e && e.message);
      return url;
    }
  }

  window.KBCornerTag = { stamp, corner: CORNER };
})();
